### PR TITLE
Add working representation for Envelope class

### PR DESCRIPTION
**Pull request by AdamCanady**

### CODE REVIEW

**Comment by tomekwojcik** [comment]
Hi,
thanks for the pull request. I feel the representation should be less verbose. Would you mind refactoring the code to return something like: `<Envelope from="from@example.com" to=["to1@example.com", "to2@example.com"] subject="My Awesome Envelope!">`?

**Comment by AdamCanady** [comment]
Check it out now. I tested with Python 2.7 and it should be good to go.

**Comment by tomekwojcik** [comment]
OK, your changes are merged into master. Thanks a lot for your input.

PS. Would you mind if I added you to `AUTHORS.rst` file?

**Comment by AdamCanady** [comment]
That would be awesome! Let me know if there's anything else I can help on!

**Pull request closed without merging**
